### ISSUE TITLE
Add setting to hide moves and time

### ISSUE THREAD

**Issue by TacoTheDank** [italankin/15Puzzle#2]
But it shows the score at the end when you complete it.

Thanks.

**Comment by italankin** [comment]
Thank you for the idea, I will probably add this feature in the 1.6.0 (within two weeks)

**Comment by italankin** [comment]
A new version with this feature will be available in Google Play in a few hours.
The setting located at 'advanced' page.

**Comment by TacoTheDank** [comment]
thanks :P
